name: flutter_blur_shower
description: "A package for showing dialogs, popups, and modal bottom sheets with blurred background."
version: 1.0.0
homepage: https://globetrotter-studio.com
repository: https://github.com/ShiKai-Pan/flutter_blur_shower
issue_tracker: https://github.com/ShiKai-Pan/flutter_blur_shower/issues

environment:
  sdk: '>=3.3.1 <4.0.0'
  flutter: ">=1.17.0"

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter: